all:
	gmkdir -p ~/Sites/7_7/ult/sugarcrm/custom/clients/base/fields/Presentationfield/
	cp *.hbs Presentationfield.js ~/Sites/7_7/ult/sugarcrm/custom/clients/base/fields/Presentationfield
	gmkdir -p ~/Sites/7_7/ult/sugarcrm/custom/modules/DynamicFields/templates/Fields/
	cp TemplatePresentationfield.php ~/Sites/7_7/ult/sugarcrm/custom/modules/DynamicFields/templates/Fields/
	gmkdir -p ~/Sites/7_7/ult/sugarcrm/custom/modules/DynamicFields/templates/Fields/Forms
	cp Presentationfield.php Presentationfield.tpl ~/Sites/7_7/ult/sugarcrm/custom/modules/DynamicFields/templates/Fields/Forms
	gmkdir -p ~/Sites/7_7/ult/sugarcrm/custom/include/SugarFields/Fields/Presentationfield
	cp SugarFieldPresentationfield.php ~/Sites/7_7/ult/sugarcrm/custom/include/SugarFields/Fields/Presentationfield
	gmkdir -p ~/Sites/7_7/ult/sugarcrm/custom/Extension/modules/ModuleBuilder/Ext/Language/
	cp en_us.Presentationfield.mb.php ~/Sites/7_7/ult/sugarcrm/custom/Extension/modules/ModuleBuilder/Ext/Language/en_us.Presentationfield.php
	gmkdir -p ~/Sites/7_7/ult/sugarcrm/custom/Extension/modules/DynamicFields/Ext/Language/
	cp en_us.Presentationfield.df.php ~/Sites/7_7/ult/sugarcrm/custom/Extension/modules/DynamicFields/Ext/Language/en_us.Presentationfield.php

