#!/usr/bin/env node

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

'use strict';

const spawnProcess = require('child_process').spawn;
const path = require('path');
const fs = require('fs');

const HOME = require('os').homedir();
const SDK_PATH = require('./get-sdk-path')();
const CORDOVA_PATH = path.resolve(SDK_PATH, 'node_modules', '.bin', 'cordova');
const NODE_VERSION = fs.readFileSync(path.resolve(SDK_PATH, '.nvmrc')).toString().trim();

let argv = process.argv.slice(2);

spawnProcess(path.resolve(HOME, '.nvm', 'nvm-exec'), [CORDOVA_PATH].concat(argv), {
    stdio: 'inherit',
    env: Object.assign({}, process.env, { NODE_VERSION })
});
