#!/usr/bin/env node

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

'use strict';

const spawnProcess = require('child_process').spawn;
const path = require('path');

const HOME = require('os').homedir();
const SDK_PATH = require('./get-sdk-path')();

const helpArgs = ['h', '-h', '/h', '--help', 'help'];

let argv = process.argv.slice(2);

if (argv.length && (helpArgs.indexOf(argv[0]) === -1)) {
    argv = argv.concat(['--app-path', __dirname]);
}

argv.push('--sdk-run');

let child = spawnProcess(path.resolve(HOME, '.nvm', 'nvm-exec'), ['./gulp'].concat(argv), {
    cwd: SDK_PATH,
    stdio: 'inherit',
});

let exitCloseErrorHandler = (codeOrError, signal) => {
    if (codeOrError || signal) {
        process.exitCode = 1;
    }
};

[ 'exit', 'close', 'error' ].forEach(eventName => child.on(eventName, exitCloseErrorHandler));
